### PR TITLE
Fix for #2

### PR DESCRIPTION
**Pull request by Hemant-Mann**
Bug Fixes
- Update Default Country in case it is not found
- Fix XML logic in LastFM

### CODE REVIEW

**Comment by bloserda** [comment]
Thanks for the pull @Hemant-Mann when load 1st page (index.php) looks good, but when click **genres** and **tracks** on the side menus the page get blank and when go to **/artist/top/** or **Artist**  menu got the same issues :
An error occurred.LastFm\Src\Error: country param invalid in C:\xampp\htdocs\application\libraries\LastFm\Src\Caller\CurlCaller.php:151 Stack trace: #0 C:\xampp\htdocs\application\libraries\LastFm\Src\Caller\Caller.php(70): LastFm\Src\Caller\CurlCaller->internalCall(Array, 'GET') #1 C:\xampp\htdocs\application\libraries\LastFm\Src\Geo.php(72): LastFm\Src\Caller\Caller->call('geo.getTopArtis...', Array) #2 C:\xampp\htdocs\application\controllers\artists.php(135): LastFm\Src\Geo::getTopArtists('US', 1) #3 [internal function]: Artists->top() #4 C:\xampp\htdocs\framework\router.php(189): call_user_func_array(Array, Array) #5 C:\xampp\htdocs\framework\router.php(126): Framework\Router->_pass('artists', 'top', Array) #6 C:\xampp\htdocs\index.php(84): Framework\Router->dispatch() #7 {main}

and how to default set playlist display when click at **Videos** menus?

**Comment by Hemant-Mann** [comment]
> and how to default set playlist display when click at Videos menus?

I have not implemented anything like this

**Comment by Hemant-Mann** [comment]
@bloserda  The PR works for me
screen shot 2017-11-24 at 9 57 35 pm

**Comment by Hemant-Mann** [comment]
@bloserda From the error log you have sent it seems some wrong value is set in your session (which was happening due to some error in master branch)
- Could you try clearing cookies or with incognito mode to see if you are facing the same problem again?

**Comment by Hemant-Mann** [comment]
@bloserda Any updates?

**Comment by Hemant-Mann** [comment]
Closing this issue as no response from the user side

**Pull request merged**
